name: Deploy PHP app to Azure Web App

on:
  push:
    branches:
      - main  # เมื่อ push ไปยัง branch main จะเริ่ม deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # เลือกเวอร์ชันที่ใช้ เช่น 7.4, 8.0, 8.1

      - name: Upload artifacts
        run: echo "Preparing package..."

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: shopping-cart
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
           package: Shopping_Cart
